package com.google.android.gms.common.api.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzcp<R extends Result> extends OptionalPendingResult<R> {
    private final zzs<R> zzfos;

    public zzcp(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zzs) {
            this.zzfos = (zzs) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public final R await() {
        return this.zzfos.await();
    }

    public final R await(long j, TimeUnit timeUnit) {
        return this.zzfos.await(j, timeUnit);
    }

    public final void cancel() {
        this.zzfos.cancel();
    }

    public final R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public final boolean isCanceled() {
        return this.zzfos.isCanceled();
    }

    public final boolean isDone() {
        return this.zzfos.isReady();
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzfos.setResultCallback(resultCallback);
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzfos.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zzfos.then(resultTransform);
    }

    public final void zza(zza zza) {
        this.zzfos.zza(zza);
    }

    public final Integer zzafr() {
        return this.zzfos.zzafr();
    }
}
